### PR TITLE
Removed support for dimensional-tf.

### PR DESCRIPTION
**Pull request by dmcclean**
Now that the dimensional-tf package has been deprecated for a considerable period, and I have gotten all packages depending on dimensional-tf to migrate to dimensional, I propose eliminating support for dimensional-tf from the atmos package.

This simplifies installation.

### CODE REVIEW

**Comment by ghorn** [comment]
thank you

**Comment by ghorn** [comment]
I just uploaded the new version to hackage http://hackage.haskell.org/package/atmos-0.4.0.0

**Comment by dmcclean** [comment]
Thanks! Sorry for the churn in dimensional/dimensional-tf/dimensional names, but we are finally have had datakinds for long enough that all that is behind us. :)

**Comment by ghorn** [comment]
no problem, thanks for keeping `atmos` up to date

**Pull request merged**
